import pygame as pg

class EventListener:
    def __init__(self) -> None: ...
    def handle_event(self, event: pg.event.Event) -> None: ...

def handle_events(event_listenters: dict[int, list[EventListener]]) -> None: ...
