import pygame as pg
import pynkie.events as events
from dataclasses import dataclass
from pynkie.model import Model as Model
from pynkie.view import View as View
from typing import NoReturn

@dataclass()
class Pynkie:
    views: list[View]
    models: list[Model]
    event_listenters: dict[int, list[events.EventListener]]
    screen_width: int = ...
    screen_height: int = ...
    max_framerate: int = ...
    debug_info: bool = ...
    use_default_cursor: bool = ...
    def run(self) -> None: ...
    def main_loop(self, display: pg.Surface, clock: pg.time.Clock) -> NoReturn: ...